-- MySQL Script generated by MySQL Workbench
-- 05/12/16 18:37:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type_Annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type_Annonce` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Annonce` (
  `id` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `date_creation` DATETIME NULL,
  `prix` INT NULL,
  `chemin_image` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `etat` ENUM('Très bon', 'Bon', 'Moyen', 'Comme neuf') NULL,
  `Utilisateur_id` INT NOT NULL,
  `Type_Annonce_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Annonce_Utilisateur1_idx` (`Utilisateur_id` ASC),
  INDEX `fk_Annonce_Type_Annonce1_idx` (`Type_Annonce_id` ASC),
  CONSTRAINT `fk_Annonce_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id`)
    REFERENCES `mydb`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Type_Annonce1`
    FOREIGN KEY (`Type_Annonce_id`)
    REFERENCES `mydb`.`Type_Annonce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `id` INT NOT NULL,
  `contenu` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Badge` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `chemin_image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Note` (
  `valeur` INT NULL,
  `commentaire` TEXT NULL,
  `acheteur` INT NOT NULL,
  `vendeur` INT NOT NULL,
  `Annonce_id` INT NOT NULL,
  INDEX `fk_Note_Utilisateur1_idx` (`acheteur` ASC),
  INDEX `fk_Note_Utilisateur2_idx` (`vendeur` ASC),
  INDEX `fk_Note_Annonce1_idx` (`Annonce_id` ASC),
  PRIMARY KEY (`vendeur`, `acheteur`, `Annonce_id`),
  CONSTRAINT `fk_Note_Utilisateur1`
    FOREIGN KEY (`acheteur`)
    REFERENCES `mydb`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Utilisateur2`
    FOREIGN KEY (`vendeur`)
    REFERENCES `mydb`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Annonce1`
    FOREIGN KEY (`Annonce_id`)
    REFERENCES `mydb`.`Annonce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mots-cles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mots-cles` (
  `id` INT NOT NULL,
  `motclef` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Annonce_Immobiliere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Annonce_Immobiliere` (
  `Annonce_id` INT NOT NULL,
  `dimensions` VARCHAR(45) NULL,
  `lignes_bus` SET('6', '8', '11') NOT NULL,
  `distance_kilometres` INT NULL,
  `distance_minutes_pieds` INT NULL,
  `distance_minutes_velo` INT NULL,
  `distance_minutes_voiture` VARCHAR(45) NULL,
  PRIMARY KEY (`Annonce_id`),
  CONSTRAINT `fk_AnnonceImmobiliere_1`
    FOREIGN KEY (`Annonce_id`)
    REFERENCES `mydb`.`Annonce` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Annonce_has_Mots-cles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Annonce_has_Mots-cles` (
  `Annonce_id` INT NOT NULL,
  `Mots-cles_id` INT NOT NULL,
  PRIMARY KEY (`Annonce_id`, `Mots-cles_id`),
  INDEX `fk_Annonce_has_Mots-cles_Mots-cles1_idx` (`Mots-cles_id` ASC),
  INDEX `fk_Annonce_has_Mots-cles_Annonce1_idx` (`Annonce_id` ASC),
  CONSTRAINT `fk_Annonce_has_Mots-cles_Annonce1`
    FOREIGN KEY (`Annonce_id`)
    REFERENCES `mydb`.`Annonce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_has_Mots-cles_Mots-cles1`
    FOREIGN KEY (`Mots-cles_id`)
    REFERENCES `mydb`.`Mots-cles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur_has_Message_about_Annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur_has_Message_about_Annonce` (
  `expediteur` INT NOT NULL,
  `Message_id` INT NOT NULL,
  `destinataire` INT NOT NULL,
  `Annonce_id` INT NOT NULL,
  PRIMARY KEY (`expediteur`, `Message_id`, `destinataire`, `Annonce_id`),
  INDEX `fk_Utilisateur_has_Message_Message1_idx` (`Message_id` ASC),
  INDEX `fk_Utilisateur_has_Message_Utilisateur1_idx` (`expediteur` ASC),
  INDEX `fk_Utilisateur_has_Message_Utilisateur2_idx` (`destinataire` ASC),
  INDEX `fk_Utilisateur_has_Message_Annonce1_idx` (`Annonce_id` ASC),
  CONSTRAINT `fk_Utilisateur_has_Message_Utilisateur1`
    FOREIGN KEY (`expediteur`)
    REFERENCES `mydb`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Message_Message1`
    FOREIGN KEY (`Message_id`)
    REFERENCES `mydb`.`Message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Message_Utilisateur2`
    FOREIGN KEY (`destinataire`)
    REFERENCES `mydb`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Message_Annonce1`
    FOREIGN KEY (`Annonce_id`)
    REFERENCES `mydb`.`Annonce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur_has_Badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur_has_Badge` (
  `Utilisateur_id` INT NOT NULL,
  `Badge_id` INT NOT NULL,
  PRIMARY KEY (`Utilisateur_id`, `Badge_id`),
  INDEX `fk_Utilisateur_has_Badge_Badge1_idx` (`Badge_id` ASC),
  INDEX `fk_Utilisateur_has_Badge_Utilisateur1_idx` (`Utilisateur_id` ASC),
  CONSTRAINT `fk_Utilisateur_has_Badge_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id`)
    REFERENCES `mydb`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Badge_Badge1`
    FOREIGN KEY (`Badge_id`)
    REFERENCES `mydb`.`Badge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
